global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nesa-node'
    static_configs:
      - targets: ['nesa-node:26660']
    metrics_path: /metrics
    scrape_interval: 5s
